### Get the secret ingredient.
 GET https://localhost:5081/secret/
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtsaW1lIiwic3ViIjoia2xpbWUiLCJqdGkiOiI2NGM4NjIzZSIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjYzMTgxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzkiLCJodHRwOi8vbG9jYWxob3N0OjUyOTgiLCJodHRwczovL2xvY2FsaG9zdDo1MDgxIl0sIm5iZiI6MTc0NDgzNTc2MCwiZXhwIjoxNzUyNjk4MTYwLCJpYXQiOjE3NDQ4MzU3NjAsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.nPCb_V3JgkMsED4oorw2f_T3WqUZ_NK1tQHKB76esIA
